module.exports = {
  CHOOSE_ESER_FROM_CLIENT: "CHOOSE_ESER_FROM_CLIENT",
  CHOOSE_ESER_FROM_SERVER: "CHOOSE_ESER_FROM_SERVER",
  ADD_MESSAGE_FROM_CLIENT: "CHOOSE_ESER_FROM_CLIENT",
  ADD_ESER_FROM_SERVER: "CHOOSE_ESER_FROM_SERVER",
  ENABLE_ESER_FROM_SERVER: "CHOOSE_ESER_FROM_SERVER"
};
